language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

install: 
  - pip install -r ./tests/tests.req

script:
  - pytest --cov=awesojson --cov-report=term-missing --cov-fail-under=100
